<center>
<div>
	<br><h1>Emergencies</h1></br>
	<br><h3>Sicurezza sul territorio</h3></br>
	<p>Crolli di porzioni di edifici, incendi o terremoti non fanno più paura!</p>
	<p>Con <b>Emergencies</b> avrai sempre a portata di click i percorsi di fuga migliori per l'evacuazione di edifici.</p>
	<p>Naviga nel sito per scoprire di più, <a href="
												<?= $this->url(array(
	                        						'controller' => 'public',
	                        						'action'     => 'login'), 
                        							'default',true
                    								);
                 								?>">effettua il login</a>
                 						o <a href="
												<?= $this->url(array(
	                        						'controller' => 'public',
	                        						'action'     => 'registrazione'), 
                        							'default',true
                    								);
                 								?>">registrati</a> per usufruire di tutti i nostri servizi!</p>
</div>
</center>
