<?php $this->headScript()
	->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js')
	->appendFile($this->baseUrl('js/functions.js'))
	->captureStart() ?>

// codice jQuery inserito da view-script nella sezione head della pagina
$(function()
{
var actionUrl='<? echo $this->url(array('controller' => 'public', 'action' => 'validateUser',), 'default');  ?>';
var formName='<?php echo $this->userForm->getName() ?>';
$(":input").on('blur', function(event) {
var formElementId = $(this).attr('id');
doValidation(formElementId, actionUrl, formName);
});
});

<?php $this->headScript()->captureEnd() ?>



<center>
	<div>
		<h2>Registrazione</h2>
		<?=$this->userForm; ?>
	</div>
</center>
