<div>
	<br><center><h1>I nostri servizi</h1></center></br>
	<p>
		Per accedere al sito l'utente deve eseguire il login o, se non è registrato, effettuare la procedura di registrazione.
		Una volta completato questo passaggio, l'utente potrà usufruire dei servizi del sito, che sono:
	</p>
	<ul>
		<li>Definire la propria posizione all'interno dell'immobile;</li>
		<li>Modificarla o, nel caso si abbandoni l'edificio, cancellarla;</li>
		<li>Segnalare eventuali situazioni di pericolo, specificando la zona in cui si trovano e il tipo di pericolo;</li>
		<li>Ricevere, in caso di pericolo, un messaggio di allerta che segnala la necessità di abbandonare l'immobile;</li>
		<li>Su richiesta, visualizzare il percorso di fuga adeguato per l'evacuazione.</li>
	</ul>
	<br><center><h3>Immobili gestiti</h3></center></br>
	<p>descrizione, piantine</p>
</div>
