<center>
<div>
	<br><h1>Chi siamo</h1></br>
	<h3>Emergencies è sinonimo di sicurezza!</h3>
	<br>
	<p>
		Emergencies è un'azienda nata nel 2004 con lo scopo di aumentare la sicurezza negli edifici.
		Da oltre dieci anni gestisce una grande varietà di immobili garantendo, in caso di terremoti, incendi, crolli o pericoli
		di altra natura, il percorso di fuga più sicuro per evacuare la struttura. Il nostro staff è costantemente al lavoro per
		la verifica, in base alle segnalazioni degli utenti, di situazioni di pericolo e per la loro segnalazione.
	</p>
</div>
</center>
